<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Anacle Starlight Meter Configuration</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/custom.js" type="text/javascript"></script>
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/main.jpg" alt="Microchip" /></div>

<div id="title"><div class="right">Anacle Starlight Series</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<!-- <a href="/index.htm">Overview</a> -->
<a href="/rt.htm" style="background:#CCCCCC; color:black">Real-Time Readings</a>
<a href="/protect/config.htm">Configuration</a>
<a href="/protect/calib.htm">Calibration</a>
<a href="/protect/compute.htm">Computation</a>
<a href="/protect/md.htm">Max Demand Settings</a>
</div>