/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_RT(void);
void HTTPPrint_status_fail(void);
void HTTPPrint_GetCalibration(void);
void HTTPPrint_config_mac(void);
void HTTPPrint_config_hostname(void);
void HTTPPrint_config_dhcpchecked(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_config_gw(void);
void HTTPPrint_config_subnet(void);
void HTTPPrint_config_dns1(void);
void HTTPPrint_config_dns2(void);
void HTTPPrint_GetMaxDemandSetting(void);
void HTTPPrint_reboot(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000000:
			HTTPIncFile((ROM BYTE*)"header.inc");
			break;
        case 0x00000001:
			HTTPIncFile((ROM BYTE*)"footer.inc");
			break;
        case 0x00000002:
			HTTPPrint_RT();
			break;
        case 0x00000003:
			HTTPPrint_status_fail();
			break;
        case 0x00000004:
			HTTPPrint_GetCalibration();
			break;
        case 0x00000006:
			HTTPPrint_config_mac();
			break;
        case 0x00000007:
			HTTPPrint_config_hostname();
			break;
        case 0x00000008:
			HTTPPrint_config_dhcpchecked();
			break;
        case 0x00000009:
			HTTPPrint_config_ip();
			break;
        case 0x0000000a:
			HTTPPrint_config_gw();
			break;
        case 0x0000000b:
			HTTPPrint_config_subnet();
			break;
        case 0x0000000c:
			HTTPPrint_config_dns1();
			break;
        case 0x0000000d:
			HTTPPrint_config_dns2();
			break;
        case 0x0000000e:
			HTTPPrint_GetMaxDemandSetting();
			break;
        case 0x0000000f:
			HTTPPrint_reboot();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
